name: Sanity test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  test_model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: iterative/setup-cml@v2

      - name: Install dependencies
        run: |
          set -e
          pip install -r requirements.txt

      - name: Authenticate to GCP
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          dvc remote modify myremote credentialpath gcp-key.json

      - name: Pull data and model from DVC
        run: |
          set -e
          dvc pull model.pkl
          dvc pull samples/sample.csv

      - name: Run unit test
        run: |
          set -e
          python -m unittest test.py > test_output.txt 2>&1 || true

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# :microscope: Model Sanity Test Report" > report.md
          echo "## Test Output" >> report.md
          echo "\`\`\`" >> report.md
          cat test_output.txt >> report.md
          echo "\`\`\`" >> report.md

          echo "## Metrics" >> report.md
          echo "\`\`\`" >> report.md
          cat metrics.txt >> report.md
          echo "\`\`\`" >> report.md

          cml comment create --publish report.md
